USE [master]
GO

/****** Object:  Database [Bibilioteca]    Script Date: 10/9/2020 20:42:23 ******/
CREATE DATABASE [Bibilioteca]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bibilioteca', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Bibilioteca.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bibilioteca_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Bibilioteca_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bibilioteca].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bibilioteca] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bibilioteca] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bibilioteca] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bibilioteca] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bibilioteca] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bibilioteca] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bibilioteca] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bibilioteca] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bibilioteca] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bibilioteca] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bibilioteca] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bibilioteca] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bibilioteca] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bibilioteca] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bibilioteca] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bibilioteca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bibilioteca] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bibilioteca] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bibilioteca] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bibilioteca] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bibilioteca] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bibilioteca] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bibilioteca] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Bibilioteca] SET  MULTI_USER 
GO

ALTER DATABASE [Bibilioteca] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bibilioteca] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bibilioteca] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bibilioteca] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bibilioteca] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bibilioteca] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Bibilioteca] SET  READ_WRITE 
GO

